scrape_configs:

  - job_name: 'spring boot app testing'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: ['localhost:8080']
        labels:
          application: 'My spring Boot Application'
